# Generated by Django 4.0.1 on 2022-01-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
