# Generated by Django 4.0.1 on 2022-01-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('amount', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('modification_date', models.DateTimeField(verbose_name='modification date')),
            ],
        ),
    ]
