# Generated by Django 4.0.1 on 2022-01-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hidden',
        ),
    ]
